version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: blog_app
    restart: always
    command: ["sh", "/entrypoint.sh"]
    volumes:
      - .:/blog_applications
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}

  celery:
    build: .
    container_name: celery_worker
    command: [ "sh", "-c", "celery -A blog_applications worker --loglevel=info" ]
    depends_on:
      - web
      - redis
      - db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}


volumes:
  postgres_data:
